---
html_document: default
author: "Erika MackeviĆ„ĀØ 6 grupĆ„ā€”"
date: '2019 m birĆ…Ā¾elis 10 d '
output:
  html_document:
    df_print: paged
  pdf_document:
    includes:
      in_header: header_lt.txt
pdf_document: default
title: "Jaunimo integracija Ć„Ć† darbo rinkĆ„ā€¦ Lietuvoje"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,collapse= TRUE, error = TRUE, warning=FALSE, message = FALSE, cache = TRUE)
```

# 1 Grafikas

```{r, echo=FALSE}
if(!require(rsdmx)) install.packages("rsdmx"):require(rsdmx)
if(!require(tidyverse)) install.packages("tidyverse"):require(tidyverse)
```

```{r, echo=FALSE}
url <- "https://osp-rs.stat.gov.lt/rest_xml/dataflow/"
meta <- readSDMX(url)
meta<- as.data.frame(meta)
```

```{r, echo=FALSE}
S3R347_M3030905_2 <- readSDMX(providerId="LSD",
                              resource = "data",
                              flowRef="S3R347_M3030905_2",
                              dsd=TRUE)
S3R347_M3030905_2 <- as.data.frame(S3R347_M3030905_2,
                                   labels=TRUE)
```

```{r, echo=FALSE}
df <- S3R347_M3030905_2 %>%
  filter((amziusM3030905 %in% c("g015g019", "g020g024", "g025g029")),
  LAIKOTARPIS>= "2013",
  Lytis_label.lt== "Vyrai ir moterys") %>%
select(-c(1,2,4:5,6,7,10:13))
```

```{r, echo=FALSE}
df2 <- df %>% group_by(LAIKOTARPIS) %>% summarize(avg=mean(obsValue, na.rm = TRUE))
```

```{r, echo=FALSE}

```

```{r, echo=FALSE, fig.height=4}
library(ggplot2)
ggplot(df2, aes(x=LAIKOTARPIS, y=avg, group=LAIKOTARPIS))+
    geom_point()+
    labs(title=" 15-29 metų jaunimo nedarbas",
         subtitle="Šaltinis: LSD",
         x="Laikotarpis",
         y="Procentai")
```

# 2 Grafikas
```{r, echo=FALSE}
if(!require(tidyverse)) install.packages("tidyverse"); require(tidyverse)
if(!require(eurostat)) install.packages("eurostat"); require(eurostat)
```

```{r, echo=FALSE}
une_rt_a <- get_eurostat("une_rt_a",
                         stringsAsFactors = FALSE,
                         filters= list(age="TOTAL",
                                       sex="T",
                                       unit="PC_POP"))
```

```{r, echo=FALSE}
df5 <- une_rt_a %>%
  filter(geo %in% c("BE", "BG", "CZ", "DK", "DE", "EE", "IE", "EL", "ES", "FR", "HR", "IT", "CY", "LV", "LT", "LU", "HU", "MT", "NL", "AT", "PL", "PT", "RO", "SI", "SK", "FI", "SE", "UK"),
         time=="2018-01-01") %>%
  select(-c(1:3,5))
```

```{r, echo=FALSE}
ggplot(df5, aes(x=reorder(geo,values), y=values))+
  geom_bar(stat= "identity",
           fill="purple")+
  labs(title="15-24 amžiaus jaunimo nedarbo lygis Europos sąjungoje",
       subtitle = "Source: Eurostat (une_rt_a)",
       x="Countries",
       y= "Percentage of total population")
```

# 3 Grafikas
```{r, echo=FALSE}

```

```{r }

```



```{r pressure, echo=FALSE}

```


